### ISSUE TITLE
Write code to send a confirmation message to the Android after a successful deposit.

### ISSUE THREAD

**Issue by drpost** [drpost/Androidchequedeposit#33]

**Comment by Truck35** [comment]
Currently working on this task.  It should be done within the next 48 hrs.

**Comment by Truck35** [comment]
WCF method that inserts data into database successfully returned comfirmation message as primitive string type.

**Comment by leoncal** [comment]
Hi Drew,
I will code the GUI for the first paper prototypes and I will include the
camera part that Ban coded. This is what I can do in the remaining time of
this semester. If I can, I will code more.
Cheers,
Humberto
