### ISSUE TITLE
Create Database Tables

### ISSUE THREAD

**Issue by drpost** [drpost/Androidchequedeposit#36]

**Comment by YaowenB** [comment]
CREATE TABLE Account_Holders (Card_number varchar(16) NOT NULL, Password varchar(20) NOT NULL, First_name varchar(25) NOT NULL, Last_name varchar(25) NOT NULL, Term_condition varchar(255) NOT NULL, PRIMARY KEY (Card_number));
CREATE TABLE Accounts (Account_Number varchar(10) NOT NULL, Card_number varchar(16) NOT NULL, Account_type varchar(1) NOT NULL, Account_balance int NOT NULL, Account_openDate datetime NOT NULL, Account_closeDate datetime NOT NULL, Daily_limit int NOT NULL, PRIMARY KEY (Account_Number));
CREATE TABLE Account_Types (Account_type varchar(1) NOT NULL, Account_description varchar(255) NOT NULL, PRIMARY KEY (Account_type));
CREATE TABLE Entity4 ();
CREATE TABLE Transactions (Transaction_id varchar(10) NOT NULL, Account_number varchar(10) NOT NULL, Amount int NOT NULL, Picture_front image NOT NULL, Picture_back image NOT NULL, [Date] datetime NOT NULL, PRIMARY KEY (Transaction_id));
CREATE UNIQUE INDEX Accounts_Account_Number ON Accounts (Account_Number);
ALTER TABLE Accounts ADD CONSTRAINT FKAccounts628492 FOREIGN KEY (Card_number) REFERENCES Account_Holders (Card_number);
ALTER TABLE Accounts ADD CONSTRAINT FKAccounts368112 FOREIGN KEY (Account_type) REFERENCES Account_Types (Account_type);
ALTER TABLE Transactions ADD CONSTRAINT FKTransactio419770 FOREIGN KEY (Account_number) REFERENCES Accounts (Account_Number);

**Comment by YaowenB** [comment]
![erd](https://cloud.githubusercontent.com/assets/11286082/6596586/26d162da-c7cc-11e4-9e28-0b0d1ab54489.png)

**Comment by bchris0912** [comment]
Hey ban don we have meeting tode?   I will be joining you in video call..
Please accept my invitation
