### ISSUE TITLE
Accept Information from Android Login request, Build database request

### ISSUE THREAD

**Issue by drpost** [drpost/Androidchequedeposit#37]

**Comment by Truck35** [comment]
A Windows Communication Foundation Method to accept log in information was successfully made and tested with a test WCF client using a windows form application.  Also, Information from the database is successfully returned upon successful login.  An message that lets the user know that their log in information is incorrect is returned if the log in is not successful.  The database information is in XML format as needed by the application running on the android device.  A primitive string type is returned if the log in is not successful.
